# Chi-Squared Goodness of Fit Test
We compare the distribution of the population (seed match set) to that of the sample (seed set), and get the pvalue of the sample drawn. 

In [1]:
from numpy import loadtxt
from scipy.stats import chisquare
import numpy as np
import pandas as pd

In [8]:
def genome_comp():
    a = 0
    t = 0
    g = 0
    c = 0
    total = 0
    filename_data = loadtxt("data/all_species_genomes.txt", comments=">",dtype="str")
    for line in filename_data:
        for char in line:
            match char:
                case 'A':
                    total +=1
                    a+=1
                case 'T':
                    total +=1
                    t+=1
                case 'C':
                    total +=1
                    c+=1
                case 'G':
                    total +=1
                    g+=1
                case _:
                    pass
    return np.array([a/total,t/total,g/total,c/total])

#SEED A's, U's, C's and G's
def seed_comp(canon_site='B'):
    #returns real coverage and seed number from mature data
    df = pd.read_csv("data/Human (Homo sapiens).csv")
    
    #We are ignoring Pre and Post for this project
    real_seeds = df['Seed']
    
    #create reverse compliments
    real_seeds = [sub.replace('A', 'X') for sub in real_seeds]
    real_seeds = [sub.replace('U', 'A') for sub in real_seeds]
    real_seeds = [sub.replace('X', 'T') for sub in real_seeds]
    real_seeds = [sub.replace('C', 'X') for sub in real_seeds]
    real_seeds = [sub.replace('G', 'C') for sub in real_seeds]
    real_seeds = [sub.replace('X', 'G') for sub in real_seeds]
    real_seeds = [sub[::-1] for sub in real_seeds]
    
    #If canon site A or C, append A at the end
    if canon_site == 'A':
        real_seeds = [item[:-1]+'A' for item in real_seeds]
    elif canon_site == 'C':
        real_seeds = [item+'A' for item in real_seeds]
    #remove repeats
    real_seeds = [*set(real_seeds)]
    count_a = sum(s.count('A') for s in real_seeds)
    count_t = sum(s.count('T') for s in real_seeds)
    count_g = sum(s.count('G') for s in real_seeds)
    count_c = sum(s.count('C') for s in real_seeds)
    
    return np.array([count_a,count_t,count_g,count_c])


In [9]:
observed = seed_comp()
total = sum(observed)
expected = genome_comp() 
expected_total = expected*total

In [10]:
expected

array([0.27491141, 0.30118026, 0.21297679, 0.21093154])

In [11]:
observed

array([674, 734, 652, 684])

In [12]:
expected_total

array([754.35689958, 826.43863186, 584.40831813, 578.79615043])

In [13]:
#perform chi-squared test
chi2_stat, p_value = chisquare(f_obs=observed, f_exp=expected_total)

print(f"Chi-squared statistic: {chi2_stat}")
print(f"P-value: {p_value}")

Chi-squared statistic: 45.83907108489761
P-value: 6.136380494055315e-10
